### ISSUE TITLE
[Customer] Deprioritized :Meta Data Based Deployments

### ISSUE THREAD

**Issue by DebGB** [retaildevcrews/pib-gitops#12]
Deprioritized as this looks like a "Nice to have" and not "Must have". Catchers do not have an appetite for this looking at the aggressive timelines they have with McD

**Comment by brijrajsingh** [comment]
A pattern to deploy applications on a fleet of Kubernetes clusters is required in which the metadata about each cluster is available in cloud as well as on edge and the releases are targeted to a set of Kubernetes clusters on the basis of the metadata.

Each edge location runs a Kubernetes cluster and is identified by an identifier number and some metadata. this metadata can be parameters like city, state, region etc, there can be more metadata that the edge knows about itself like CPU family, operating system version and other details.
This metadata should be available in cloud and the devops team should be able to target releases by the metadata - for ex - Target release V1.1.1 to all edge devices in Florida state .

Kubernetes clusters running on edge boxes should be able to send metadata about themselves and the platform should be able to add more metadata to a given cluster/s.

**Customer Scenario** 

The Customer have a fleet of Kubernetes clusters (each cluster is an edge device with MicroK8s), Each device runs in a store with some metadata like which store id, location, region and other metadata. 
Each edge location runs a Kubernetes cluster and is identified by an identifier number and some metadata. this metadata can be parameters like city, state, region etc, there can be more metadata that the edge knows about itself like CPU family, operating system version and other details.
This metadata should be available in cloud and the devops team should be able to target releases by the metadata - for ex - Target release V1.1.1 to all edge devices in Florida state .

**Comment by bartr** [comment]
closing as dupe
